### PR TITLE
Provided Light Theme / Dark Theme using Material theme

### PR DESCRIPTION
**Pull request by Amit-4186**
Refactored theme to follow Material Design standards by removing explicit colour specifications. Also cleaned up some unnecessary imports. @yuvrajsinghgmx please add "hacktoberfest-accepted" label to this PR.

Screenshot_20241006_010608_ShopSmart
Screenshot_20241006_010649_ShopSmart

Screenshot_20241006_010710_ShopSmart

### CODE REVIEW

**Comment by Muhasif-Hafiz** [comment]
Issue:
There is a duplication of the bottom Bar parameter within the Scaffold composable, which will lead to a compilation error. @Amit-4186  please fix it

**Comment by Amit-4186** [comment]
> Issue: There is a duplication of the bottom Bar parameter within the Scaffold composable, which will lead to a compilation error. @Amit-4186 please fix it

@Muhasif-Hafiz Thank you for the feedback! I double-checked the code, and it seems there's only one instance of the bottomBar parameter.
Maybe you confused it with topAppBar.
Also I have ran the app without any error. 
Could you please have another look and let me know if I missed something?"

**Comment by Amit-4186** [comment]
@yuvrajsinghgmx Please add hacktoberfest-accepted, gssoc-exp and level label to the PR if you consider valid. Thnx

**Comment by Muhasif-Hafiz** [comment]
@Amit-4186  works fine.. thanks

**Pull request merged**
