### PR TITLE
Added favorites screen #61

### PR DESCRIPTION
**Pull request by Amit-4186**
- Added favorites screen along with favorite button on shopping #61 

- Fixed issue - two data classes for Product instead of one

### CODE REVIEW

**Comment by yuvrajsinghgmx** [comment]
@Amit-4186 Can you please share a screenshot or a screen recording from your side.

**Comment by Amit-4186** [comment]
@yuvrajsinghgmx Here are the screenshots
Suggest me any changes if required.
Screenshot_2024-10-19-14-44-44-20_2e866dd9837e72077c6daae78cc2bc15
Screenshot_2024-10-19-14-44-47-35_2e866dd9837e72077c6daae78cc2bc15

**Comment by yuvrajsinghgmx** [comment]
Remove the Upcoming Navigation Item and please push correctly because i can see from your previous PR only 55 lines of code were changes and the FavoritesScreen file was missing too.

**Comment by Amit-4186** [comment]
@yuvrajsinghgmx Sorry for wrongly commiting. I forgot to add the fav screen to the commit.
Also i wanted to ask how am i supposed to add items to favorites screen when there will be no favorite button on the main shopping list.

**Comment by yuvrajsinghgmx** [comment]
> @yuvrajsinghgmx Sorry for wrongly commiting. I forgot to add the fav screen to the commit.
> Also i wanted to ask how am i supposed to add items to favorites screen when there will be no favorite button on the main shopping list.

Items will be added from other pages such as homepage,search page, product details page.

**Pull request merged**
