### PR TITLE
Changed from list view to Grid view.

### PR DESCRIPTION
**Pull request by Amit-4186**
A better looking UI with two column lazy grid. #62 

> @yuvrajsinghgmx Please add labels to the PR and tell me if in case you want changes.

Screenshot_20241009_194302_ShopSmart 1

### CODE REVIEW

**Comment by Avinash-Codes** [comment]
Because of this merge, my previous work, where items were added in sorted order by days, has been discarded. Please fix that. Also, I don't think it looks that good.

**Comment by yuvrajsinghgmx** [comment]
Yes i was also thinking that the items are taking much more space.
@Amit-4186 I am reverting this merge you will still get the points.

**Comment by Amit-4186** [comment]
> Yes i was also thinking that the items are taking much more space. @Amit-4186 I am reverting this merge you will still get the points.

Its Fine even if i don't get points. Let me know if such a change is required.

**Comment by yuvrajsinghgmx** [comment]
The Images inside the grid layout were taking so much space only 4 items were visible at one time but by using List we can show up to 6-8 items with images.

**Pull request merged**
